### ISSUE TITLE
'int' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by devika28** [ChihebTrabelsi/deep_complex_networks#1]
Hi,
When I try to `python scripts/run.py train -d ./data/ -w ./ --model complex --sf 5 --nb 5` it throws the following error. Whats the fix?

![screenshot from 2017-06-18 16-09-47](https://user-images.githubusercontent.com/29524182/27263859-9ed03614-5440-11e7-8c5e-fb1f60ce3646.png)

These are my model parameters and system settings 

![modelp](https://user-images.githubusercontent.com/29524182/27263873-e6651418-5440-11e7-8c96-520c78ee9d2e.png)

Thank you

**Comment by ChihebTrabelsi** [comment]
You are using tensorflow backend. You should use Theano backend. In order to use theano backend, you should follow the instructions given here `https://keras.io/backend/#switching-from-one-backend-to-another`. Here below, you can find what your keras.json file should contain as information:
`
{
    "image_data_format": "channels_first",
    "epsilon": 1e-07,
    "floatx": "float32",
    "backend": "theano"
}
`

**Comment by devika28** [comment]
Thanks! that worked for me

**Comment by tangye95** [comment]
@devika28  hi, sorry to bother you, I am a new user of deep learning framework, could you please tell me before you trying "python scripts/run.py train -d ./data/ -w ./ --model complex --sf 5 --nb 5", do you set up something, like set data_path = ./xxx

**Comment by tangye95** [comment]
before you try the command, I think you should see thishttps://fuel.readthedocs.io/en/latest/built_in_datasets.html  
 to avoid  ConfigurationError
