### ISSUE TITLE
question about data_path

### ISSUE THREAD

**Issue by DeanLee-CHN** [ChihebTrabelsi/deep_complex_networks#14]
Hello,
I'm trying to run the complex model on cifar-10 dataset,but errors occur like this:
![image](https://user-images.githubusercontent.com/11832829/33027452-17076a58-ce4e-11e7-9715-8b6d745b2de5.png)
I've typed the '-d $datapath' in the command,then I went to check the argparser as the error mentioned,but I still cannot figure it out.
I'm really sorry to interrupt you,and really expect a explanation of the error.
Best wishes.
Thanks a lot.

**Comment by tangye95** [comment]
https://fuel.readthedocs.io/en/latest/built_in_datasets.html
the problem is caused by fuel

**Comment by frozoul** [comment]
@tangye95 I'm sorry but I don't know how to solve this problem,the fuel's doc is confused me,which things should I follow by the code "-d "? Should the path of data in quotes or not?

**Comment by dmitriy-serdyuk** [comment]
[This section](https://fuel.readthedocs.io/en/latest/built_in_datasets.html#environment-variable) describes it
