### ISSUE TITLE
Problem about installation

### ISSUE THREAD

**Issue by yannan123** [ChihebTrabelsi/deep_complex_networks#22]
When I install requirements for music experiments, it gives me this error, please help me, thanks

(D:\anaconda3) C:\Users\123>pip install git+git://github.com/bartvm/mimir.git
Collecting git+git://github.com/bartvm/mimir.git
  Cloning git://github.com/bartvm/mimir.git to c:\users\123\appdata\local\temp\pip-4md_br_o-build
Requirement already satisfied: pyzmq in d:\anaconda3\lib\site-packages (from mimir==0.1.dev1)
Requirement already satisfied: six in d:\anaconda3\lib\site-packages (from mimir==0.1.dev1)
Requirement already satisfied: simplejson in d:\anaconda3\lib\site-packages (from mimir==0.1.dev1)
Installing collected packages: mimir
  Running setup.py install for mimir ... error
    Complete output from command d:\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\123\\AppData\\Local\\Temp\\pip-4md_br_o-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\123\AppData\Local\Temp\pip-crye2e8k-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\mimir
    copying mimir\formatters.py -> build\lib.win-amd64-3.6\mimir
    copying mimir\handlers.py -> build\lib.win-amd64-3.6\mimir
    copying mimir\logger.py -> build\lib.win-amd64-3.6\mimir
    copying mimir\plot.py -> build\lib.win-amd64-3.6\mimir
    copying mimir\remote.py -> build\lib.win-amd64-3.6\mimir
    copying mimir\serialization.py -> build\lib.win-amd64-3.6\mimir
    copying mimir\stream.py -> build\lib.win-amd64-3.6\mimir
    copying mimir\utils.py -> build\lib.win-amd64-3.6\mimir
    copying mimir\__init__.py -> build\lib.win-amd64-3.6\mimir
    running build_ext
    error: [WinError 2] 系统找不到指定的文件。

    ----------------------------------------
Command "d:\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\123\\AppData\\Local\\Temp\\pip-4md_br_o-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\123\AppData\Local\Temp\pip-crye2e8k-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\123\AppData\Local\Temp\pip-4md_br_o-build\

**Comment by dmitriy-serdyuk** [comment]
Yep, windows is not supported. You can try to patch it and make a PR.
