### ISSUE TITLE
about training

### ISSUE THREAD

**Issue by BinglinShu** [ChihebTrabelsi/deep_complex_networks#3]
![image](https://user-images.githubusercontent.com/29726904/27578487-d84c2ed0-5b56-11e7-8a9e-1e1b267e0463.png)
How to solve this problem:Attribute error:'int' object has no attribute 'dtype'? Thanks

**Comment by ChihebTrabelsi** [comment]
It is the exact same issue than #1 You can find there the solution for the problem.

**Comment by BinglinShu** [comment]
thanks!

**Comment by Musawar71** [comment]
can i train this network on 3d dataset
