### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Logger'

### ISSUE THREAD

**Issue by martinmamql** [ChihebTrabelsi/deep_complex_networks#34]
Hi,
When I try to run `python scripts/train.py shallow_model --in-memory --model=shallow_convnet --local-data data/musicnet_11khz.npz` in the `musicnet/` folder, I encounter the following error:

`Traceback (most recent call last):
  File "scripts/train.py", line 142, in <module>
    main(**parser.parse_args().__dict__)
  File "scripts/train.py", line 111, in main
    logger = mimir.logger(
AttributeError: 'module' object has no attribute 'logger'
`

I then open`python` and do:`import mimir; mimir.Logger(maxlen=10)`
The same error occurs:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'Logger'
`
I have checked the docs of mimir and didn't find this issue. May I ask what the problem might be? Thanks!

**Comment by martinmamql** [comment]
Problem solved! Installed wrong mimir. Thank you!

**Comment by hanqinnan** [comment]
I also have this issue,hou can I find and install right mimir

**Comment by hanqinnan** [comment]
> Problem solved! Installed wrong mimir. Thank you!

I also have this issue,hou can I find and install right mimir

**Comment by xiao333ma** [comment]
> Problem solved! Installed wrong mimir. Thank you!

same issue, which version `mimir` should i use? plz help me

**Comment by martinmamql** [comment]
Could you try this:
https://github.com/muqiaoy/mimir
