### ISSUE TITLE
about complex training

### ISSUE THREAD

**Issue by BinglinShu** [ChihebTrabelsi/deep_complex_networks#4]
![image](https://user-images.githubusercontent.com/29726904/27626173-ae8e6662-5c19-11e7-9448-e518523ad146.png)
How to solve this problem:'ValueError:Operands could not be broadcast together with shape(32,16,44)(32,16,22)?'Thanks!

**Comment by ChihebTrabelsi** [comment]
can you post the command that you have executed?

**Comment by BinglinShu** [comment]
when '--model' choose 'real',it's ok! but when choose 'complex' ,it's not work.
Thanks a lot!






------------------ 原始邮件 ------------------
发件人: "ChihebTrabelsi";<notifications@github.com>;
发送时间: 2017年6月30日(星期五) 上午6:05
收件人: "ChihebTrabelsi/deep_complex_networks"<deep_complex_networks@noreply.github.com>; 
抄送: "c200l"<491476173@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ChihebTrabelsi/deep_complex_networks] about complex training(#4)




can you post the command that you have executed?

**Comment by ChihebTrabelsi** [comment]
can you post the exact command that generated the error?

**Comment by BinglinShu** [comment]
The command I have coded is that:





------------------ 原始邮件 ------------------
发件人: "ChihebTrabelsi";<notifications@github.com>;
发送时间: 2017年7月3日(星期一) 凌晨3:12
收件人: "ChihebTrabelsi/deep_complex_networks"<deep_complex_networks@noreply.github.com>; 
抄送: "c200l"<491476173@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ChihebTrabelsi/deep_complex_networks] about complex training(#4)




can you post the exact command that generated the error?

**Comment by ChihebTrabelsi** [comment]
You haven't written the command. Can you please post it so I can investigate the cause of the error. Thank you.

**Comment by HKCaesar** [comment]
Hi ,
 I have input cmds  is that:
python scripts/run.py train --model complex 
--------------------
Traceback (most recent call last):
  File "scripts/run.py", line 230, in <module>
    main(sys.argv)
  File "scripts/run.py", line 228, in main
    return d.__subcmdfn__(d)
  File "scripts/run.py", line 186, in run
    import training;training.train(d)
  File /workspace/dl/keras/theao/deep_complex_networks/scripts/training.py", line 605, in train
    model = getResnetModel(d)
  File "/workspace/dl/keras/theao/deep_complex_networks/scripts/training.py", line 213, in getResnetModel
    O = getResidualBlock(O, filsize, [sf*2, sf*2], 3, str(i+1), 'regular', convArgs, bnArgs, d)
  File "/workspace/dl/keras/theao/deep_complex_networks/scripts/training.py", line 108, in getResidualBlock
    O= Add()([O, I])
  File /miniconda2/envs/CSCW/lib/python2.7/site-packages/keras/engine/topology.py", line 571, in __call__
    self.build(input_shapes)
  File /miniconda2/envs/CSCW/lib/python2.7/site-packages/keras/layers/merge.py", line 84, in build
    output_shape = self._compute_elemwise_op_output_shape(output_shape, shape)
  File /miniconda2/envs/CSCW/lib/python2.7/site-packages/keras/layers/merge.py", line 55, in _compute_elemwise_op_output_shape
    str(shape1) + ' ' + str(shape2))
ValueError: Operands could not be broadcast together with shapes (32, 16, 44) (32, 16, 22)

As is shown, shape of I & O do not match exactly.
Thanks!

**Comment by ChihebTrabelsi** [comment]
the following command `python scripts/run.py train --model complex` works fine for me.

**Comment by HKCaesar** [comment]
oh，thanks! It a amzing work!
It looks that the env matters when compiling! 
Centos 7.0 , x86_64.

**Comment by CedricChing** [comment]
I've encountered the same problem.How did you solve it?

**Comment by HKCaesar** [comment]
sorry 。 I depend on machine os version when copiling.I have not got it。

CIEE of CAU  Q.Q.Zhang

**Comment by BinglinShu** [comment]
the code(use tensorflow backend):

when I use ComplexBN,It doesn't work,thank you for your help!
------------------ 原始邮件 ------------------
发件人: "ChihebTrabelsi";<notifications@github.com>;
发送时间: 2017年7月16日(星期天) 中午12:38
收件人: "ChihebTrabelsi/deep_complex_networks"<deep_complex_networks@noreply.github.com>;
抄送: "c200l"<491476173@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ChihebTrabelsi/deep_complex_networks] about complex training(#4)




Closed #4.

**Comment by bruceyo** [comment]
I also encountered the same problem by feeding the dataset cifar10 with shape of (N, 3, 32, 32) and my own dataset with shape of (N, 3, 300, 50). Could you provide  @ChihebTrabelsi?
